# Generated by Django 4.0.4 on 2022-05-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default=2, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
