# Generated by Django 4.0.4 on 2022-05-27 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_novel_active_alter_novel_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='active',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='novel',
            name='active',
            field=models.BooleanField(),
        ),
    ]
