# Generated by Django 4.0.4 on 2022-05-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapterOrder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
