# Generated by Django 4.0.4 on 2022-05-28 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_chapter_chapterorder_alter_chapter_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='first_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='novel',
            name='url',
            field=models.CharField(max_length=34),
        ),
    ]
