from django import forms

class NovelForm(forms.Form):
    taglist = [('Abandoned Children', 'Abandoned Children'),
 ('Ability Steal', 'Ability Steal'),
 ('Absent Parents', 'Absent Parents'),
 ('Abusive Characters', 'Abusive Characters'),
 ('Academy', 'Academy'),
 ('Accelerated Growth', 'Accelerated Growth'),
 ('Acting', 'Acting'),
 ('Adapted from Manga', 'Adapted from Manga'),
 ('Adapted from Manhua', 'Adapted from Manhua'),
 ('Adapted to Anime', 'Adapted to Anime'),
 ('Adapted to Drama', 'Adapted to Drama'),
 ('Adapted to Drama CD', 'Adapted to Drama CD'),
 ('Adapted to Game', 'Adapted to Game'),
 ('Adapted to Manga', 'Adapted to Manga'),
 ('Adapted to Manhua', 'Adapted to Manhua'),
 ('Adapted to Manhwa', 'Adapted to Manhwa'),
 ('Adapted to Movie', 'Adapted to Movie'),
 ('Adapted to Visual Novel', 'Adapted to Visual Novel'),
 ('Adopted Children', 'Adopted Children'),
 ('Adopted Protagonist', 'Adopted Protagonist'),
 ('Adultery', 'Adultery'),
 ('Adventurers', 'Adventurers'),
 ('Affair', 'Affair'),
 ('Age Progression', 'Age Progression'),
 ('Age Regression', 'Age Regression'),
 ('Aggressive Characters', 'Aggressive Characters'),
 ('Alchemy', 'Alchemy'),
 ('Aliens', 'Aliens'),
 ('All-Girls School', 'All-Girls School'),
 ('Alternate World', 'Alternate World'),
 ('Amnesia', 'Amnesia'),
 ('Amusement Park', 'Amusement Park'),
 ('Anal', 'Anal'),
 ('Ancient China', 'Ancient China'),
 ('Ancient Times', 'Ancient Times'),
 ('Androgynous Characters', 'Androgynous Characters'),
 ('Androids', 'Androids'),
 ('Angels', 'Angels'),
 ('Animal Characteristics', 'Animal Characteristics'),
 ('Animal Rearing', 'Animal Rearing'),
 ('Anti-Magic', 'Anti-Magic'),
 ('Anti-social Protagonist', 'Anti-social Protagonist'),
 ('Antihero Protagonist', 'Antihero Protagonist'),
 ('Antique Shop', 'Antique Shop'),
 ('Apartment Life', 'Apartment Life'),
 ('Apathetic Protagonist', 'Apathetic Protagonist'),
 ('Apocalypse', 'Apocalypse'),
 ('Appearance Changes', 'Appearance Changes'),
 ('Appearance Different from Actual Age',
  'Appearance Different from Actual Age'),
 ('Archery', 'Archery'),
 ('Aristocracy', 'Aristocracy'),
 ('Arms Dealers', 'Arms Dealers'),
 ('Army', 'Army'),
 ('Army Building', 'Army Building'),
 ('Arranged Marriage', 'Arranged Marriage'),
 ('Arrogant Characters', 'Arrogant Characters'),
 ('Artifact Crafting', 'Artifact Crafting'),
 ('Artifacts', 'Artifacts'),
 ('Artificial Intelligence', 'Artificial Intelligence'),
 ('Artists', 'Artists'),
 ('Assassins', 'Assassins'),
 ('Astrologers', 'Astrologers'),
 ('Autism', 'Autism'),
 ('Automatons', 'Automatons'),
 ('Average-looking Protagonist', 'Average-looking Protagonist'),
 ('Award-winning Work', 'Award-winning Work'),
 ('Awkward Protagonist', 'Awkward Protagonist'),
 ('Bands', 'Bands'),
 ('Based on a Movie', 'Based on a Movie'),
 ('Based on a Song', 'Based on a Song'),
 ('Based on a TV Show', 'Based on a TV Show'),
 ('Based on a Video Game', 'Based on a Video Game'),
 ('Based on a Visual Novel', 'Based on a Visual Novel'),
 ('Based on an Anime', 'Based on an Anime'),
 ('Battle Academy', 'Battle Academy'),
 ('Battle Competition', 'Battle Competition'),
 ('BDSM', 'BDSM'),
 ('Beast Companions', 'Beast Companions'),
 ('Beastkin', 'Beastkin'),
 ('Beasts', 'Beasts'),
 ('Beautiful Female Lead', 'Beautiful Female Lead'),
 ('Bestiality', 'Bestiality'),
 ('Betrayal', 'Betrayal'),
 ('Bickering Couple', 'Bickering Couple'),
 ('Biochip', 'Biochip'),
 ('Bisexual Protagonist', 'Bisexual Protagonist'),
 ('Black Belly', 'Black Belly'),
 ('Blackmail', 'Blackmail'),
 ('Blacksmith', 'Blacksmith'),
 ('Blind Dates', 'Blind Dates'),
 ('Blind Protagonist', 'Blind Protagonist'),
 ('Blood Manipulation', 'Blood Manipulation'),
 ('Bloodlines', 'Bloodlines'),
 ('Body Swap', 'Body Swap'),
 ('Body Tempering', 'Body Tempering'),
 ('Body-double', 'Body-double'),
 ('Bodyguards', 'Bodyguards'),
 ('Books', 'Books'),
 ('Bookworm', 'Bookworm'),
 ('Boss-Subordinate Relationship', 'Boss-Subordinate Relationship'),
 ('Brainwashing', 'Brainwashing'),
 ('Breast Fetish', 'Breast Fetish'),
 ('Broken Engagement', 'Broken Engagement'),
 ('Brother Complex', 'Brother Complex'),
 ('Brotherhood', 'Brotherhood'),
 ('Buddhism', 'Buddhism'),
 ('Bullying', 'Bullying'),
 ('Business Management', 'Business Management'),
 ('Businessmen', 'Businessmen'),
 ('Butlers', 'Butlers'),
 ('Calm Protagonist', 'Calm Protagonist'),
 ('Cannibalism', 'Cannibalism'),
 ('Card Games', 'Card Games'),
 ('Carefree Protagonist', 'Carefree Protagonist'),
 ('Caring Protagonist', 'Caring Protagonist'),
 ('Cautious Protagonist', 'Cautious Protagonist'),
 ('Celebrities', 'Celebrities'),
 ('Character Growth', 'Character Growth'),
 ('Charismatic Protagonist', 'Charismatic Protagonist'),
 ('Charming Protagonist', 'Charming Protagonist'),
 ('Chat Rooms', 'Chat Rooms'),
 ('Cheats', 'Cheats'),
 ('Chefs', 'Chefs'),
 ('Child Abuse', 'Child Abuse'),
 ('Child Protagonist', 'Child Protagonist'),
 ('Childcare', 'Childcare'),
 ('Childhood Friends', 'Childhood Friends'),
 ('Childhood Love', 'Childhood Love'),
 ('Childhood Promise', 'Childhood Promise'),
 ('Childish Protagonist', 'Childish Protagonist'),
 ('Chuunibyou', 'Chuunibyou'),
 ('Clan Building', 'Clan Building'),
 ('Classic', 'Classic'),
 ('Clever Protagonist', 'Clever Protagonist'),
 ('Clingy Lover', 'Clingy Lover'),
 ('Clones', 'Clones'),
 ('Clubs', 'Clubs'),
 ('Clumsy Love Interests', 'Clumsy Love Interests'),
 ('Co-Workers', 'Co-Workers'),
 ('Cohabitation', 'Cohabitation'),
 ('Cold Love Interests', 'Cold Love Interests'),
 ('Cold Protagonist', 'Cold Protagonist'),
 ('Collection of Short Stories', 'Collection of Short Stories'),
 ('College/University', 'College/University'),
 ('Coma', 'Coma'),
 ('Comedic Undertone', 'Comedic Undertone'),
 ('Coming of Age', 'Coming of Age'),
 ('Complex Family Relationships', 'Complex Family Relationships'),
 ('Conditional Power', 'Conditional Power'),
 ('Confident Protagonist', 'Confident Protagonist'),
 ('Confinement', 'Confinement'),
 ('Conflicting Loyalties', 'Conflicting Loyalties'),
 ('Contracts', 'Contracts'),
 ('Cooking', 'Cooking'),
 ('Corruption', 'Corruption'),
 ('Cosmic Wars', 'Cosmic Wars'),
 ('Cosplay', 'Cosplay'),
 ('Couple Growth', 'Couple Growth'),
 ('Court Official', 'Court Official'),
 ('Cousins', 'Cousins'),
 ('Cowardly Protagonist', 'Cowardly Protagonist'),
 ('Crafting', 'Crafting'),
 ('Crime', 'Crime'),
 ('Criminals', 'Criminals'),
 ('Cross-dressing', 'Cross-dressing'),
 ('Crossover', 'Crossover'),
 ('Cruel Characters', 'Cruel Characters'),
 ('Cryostasis', 'Cryostasis'),
 ('Cultivation', 'Cultivation'),
 ('Cunnilingus', 'Cunnilingus'),
 ('Cunning Protagonist', 'Cunning Protagonist'),
 ('Curious Protagonist', 'Curious Protagonist'),
 ('Curses', 'Curses'),
 ('Cute Children', 'Cute Children'),
 ('Cute Protagonist', 'Cute Protagonist'),
 ('Cute Story', 'Cute Story'),
 ('Dancers', 'Dancers'),
 ('Dao Companion', 'Dao Companion'),
 ('Dao Comprehension', 'Dao Comprehension'),
 ('Daoism', 'Daoism'),
 ('Dark', 'Dark'),
 ('Dead Protagonist', 'Dead Protagonist'),
 ('Death', 'Death'),
 ('Death of Loved Ones', 'Death of Loved Ones'),
 ('Debts', 'Debts'),
 ('Delinquents', 'Delinquents'),
 ('Delusions', 'Delusions'),
 ('Demi-Humans', 'Demi-Humans'),
 ('Demon Lord', 'Demon Lord'),
 ('Demonic Cultivation Technique', 'Demonic Cultivation Technique'),
 ('Demons', 'Demons'),
 ('Dense Protagonist', 'Dense Protagonist'),
 ('Depictions of Cruelty', 'Depictions of Cruelty'),
 ('Depression', 'Depression'),
 ('Destiny', 'Destiny'),
 ('Detectives', 'Detectives'),
 ('Determined Protagonist', 'Determined Protagonist'),
 ('Devoted Love Interests', 'Devoted Love Interests'),
 ('Different Social Status', 'Different Social Status'),
 ('Disabilities', 'Disabilities'),
 ('Discrimination', 'Discrimination'),
 ('Disfigurement', 'Disfigurement'),
 ('Dishonest Protagonist', 'Dishonest Protagonist'),
 ('Distrustful Protagonist', 'Distrustful Protagonist'),
 ('Divination', 'Divination'),
 ('Divine Protection', 'Divine Protection'),
 ('Divorce', 'Divorce'),
 ('Doctors', 'Doctors'),
 ('Dolls/Puppets', 'Dolls/Puppets'),
 ('Domestic Affairs', 'Domestic Affairs'),
 ('Doting Love Interests', 'Doting Love Interests'),
 ('Doting Older Siblings', 'Doting Older Siblings'),
 ('Doting Parents', 'Doting Parents'),
 ('Dragon Riders', 'Dragon Riders'),
 ('Dragon Slayers', 'Dragon Slayers'),
 ('Dragons', 'Dragons'),
 ('Dreams', 'Dreams'),
 ('Drugs', 'Drugs'),
 ('Druids', 'Druids'),
 ('Dungeon Master', 'Dungeon Master'),
 ('Dungeons', 'Dungeons'),
 ('Dwarfs', 'Dwarfs'),
 ('Dystopia', 'Dystopia'),
 ('e-Sports', 'e-Sports'),
 ('Early Romance', 'Early Romance'),
 ('Earth Invasion', 'Earth Invasion'),
 ('Easy Going Life', 'Easy Going Life'),
 ('Economics', 'Economics'),
 ('Editors', 'Editors'),
 ('Eidetic Memory', 'Eidetic Memory'),
 ('Elderly Protagonist', 'Elderly Protagonist'),
 ('Elemental Magic', 'Elemental Magic'),
 ('Elves', 'Elves'),
 ('Emotionally Weak Protagonist', 'Emotionally Weak Protagonist'),
 ('Empires', 'Empires'),
 ('Enemies Become Allies', 'Enemies Become Allies'),
 ('Enemies Become Lovers', 'Enemies Become Lovers'),
 ('Engagement', 'Engagement'),
 ('Engineer', 'Engineer'),
 ('Enlightenment', 'Enlightenment'),
 ('Episodic', 'Episodic'),
 ('Eunuch', 'Eunuch'),
 ('European Ambience', 'European Ambience'),
 ('Evil Gods', 'Evil Gods'),
 ('Evil Organizations', 'Evil Organizations'),
 ('Evil Protagonist', 'Evil Protagonist'),
 ('Evil Religions', 'Evil Religions'),
 ('Evolution', 'Evolution'),
 ('Exhibitionism', 'Exhibitionism'),
 ('Exorcism', 'Exorcism'),
 ('Eye Powers', 'Eye Powers'),
 ('Fairies', 'Fairies'),
 ('Fallen Angels', 'Fallen Angels'),
 ('Fallen Nobility', 'Fallen Nobility'),
 ('Familial Love', 'Familial Love'),
 ('Familiars', 'Familiars'),
 ('Family', 'Family'),
 ('Family Business', 'Family Business'),
 ('Family Conflict', 'Family Conflict'),
 ('Famous Parents', 'Famous Parents'),
 ('Famous Protagonist', 'Famous Protagonist'),
 ('Fanaticism', 'Fanaticism'),
 ('Fanfiction', 'Fanfiction'),
 ('Fantasy Creatures', 'Fantasy Creatures'),
 ('Fantasy World', 'Fantasy World'),
 ('Farming', 'Farming'),
 ('Fast Cultivation', 'Fast Cultivation'),
 ('Fast Learner', 'Fast Learner'),
 ('Fat Protagonist', 'Fat Protagonist'),
 ('Fat to Fit', 'Fat to Fit'),
 ('Fated Lovers', 'Fated Lovers'),
 ('Fearless Protagonist', 'Fearless Protagonist'),
 ('Fellatio', 'Fellatio'),
 ('Female Master', 'Female Master'),
 ('Female Protagonist', 'Female Protagonist'),
 ('Female to Male', 'Female to Male'),
 ('Feng Shui', 'Feng Shui'),
 ('Firearms', 'Firearms'),
 ('First Love', 'First Love'),
 ('First-time Intercourse', 'First-time Intercourse'),
 ('Flashbacks', 'Flashbacks'),
 ('Fleet Battles', 'Fleet Battles'),
 ('Folklore', 'Folklore'),
 ('Forced into a Relationship', 'Forced into a Relationship'),
 ('Forced Living Arrangements', 'Forced Living Arrangements'),
 ('Forced Marriage', 'Forced Marriage'),
 ('Forgetful Protagonist', 'Forgetful Protagonist'),
 ('Former Hero', 'Former Hero'),
 ('Fox Spirits', 'Fox Spirits'),
 ('Friends Become Enemies', 'Friends Become Enemies'),
 ('Friendship', 'Friendship'),
 ('Fujoshi', 'Fujoshi'),
 ('Futanari', 'Futanari'),
 ('Futuristic Setting', 'Futuristic Setting'),
 ('Galge', 'Galge'),
 ('Gambling', 'Gambling'),
 ('Game Elements', 'Game Elements'),
 ('Game Ranking System', 'Game Ranking System'),
 ('Gamers', 'Gamers'),
 ('Gangs', 'Gangs'),
 ('Gate to Another World', 'Gate to Another World'),
 ('Genderless Protagonist', 'Genderless Protagonist'),
 ('Generals', 'Generals'),
 ('Genetic Modifications', 'Genetic Modifications'),
 ('Genies', 'Genies'),
 ('Genius Protagonist', 'Genius Protagonist'),
 ('Ghosts', 'Ghosts'),
 ('Gladiators', 'Gladiators'),
 ('Glasses-wearing Love Interests', 'Glasses-wearing Love Interests'),
 ('Glasses-wearing Protagonist', 'Glasses-wearing Protagonist'),
 ('Goblins', 'Goblins'),
 ('God Protagonist', 'God Protagonist'),
 ('God-human Relationship', 'God-human Relationship'),
 ('Goddesses', 'Goddesses'),
 ('Godly Powers', 'Godly Powers'),
 ('Gods', 'Gods'),
 ('Golems', 'Golems'),
 ('Gore', 'Gore'),
 ('Grave Keepers', 'Grave Keepers'),
 ('Grinding', 'Grinding'),
 ('Guardian Relationship', 'Guardian Relationship'),
 ('Guilds', 'Guilds'),
 ('Gunfighters', 'Gunfighters'),
 ('Hackers', 'Hackers'),
 ('Half-human Protagonist', 'Half-human Protagonist'),
 ('Handjob', 'Handjob'),
 ('Handsome Male Lead', 'Handsome Male Lead'),
 ('Hard-Working Protagonist', 'Hard-Working Protagonist'),
 ('Harem-seeking Protagonist', 'Harem-seeking Protagonist'),
 ('Harsh Training', 'Harsh Training'),
 ('Hated Protagonist', 'Hated Protagonist'),
 ('Healers', 'Healers'),
 ('Heartwarming', 'Heartwarming'),
 ('Heaven', 'Heaven'),
 ('Heavenly Tribulation', 'Heavenly Tribulation'),
 ('Hell', 'Hell'),
 ('Helpful Protagonist', 'Helpful Protagonist'),
 ('Herbalist', 'Herbalist'),
 ('Heroes', 'Heroes'),
 ('Heterochromia', 'Heterochromia'),
 ('Hidden Abilities', 'Hidden Abilities'),
 ('Hiding True Abilities', 'Hiding True Abilities'),
 ('Hiding True Identity', 'Hiding True Identity'),
 ('Hikikomori', 'Hikikomori'),
 ('Homunculus', 'Homunculus'),
 ('Honest Protagonist', 'Honest Protagonist'),
 ('Hospital', 'Hospital'),
 ('Hot-blooded Protagonist', 'Hot-blooded Protagonist'),
 ('Human Experimentation', 'Human Experimentation'),
 ('Human Weapon', 'Human Weapon'),
 ('Human-Nonhuman Relationship', 'Human-Nonhuman Relationship'),
 ('Humanoid Protagonist', 'Humanoid Protagonist'),
 ('Hunters', 'Hunters'),
 ('Hypnotism', 'Hypnotism'),
 ('Identity Crisis', 'Identity Crisis'),
 ('Imaginary Friend', 'Imaginary Friend'),
 ('Immortals', 'Immortals'),
 ('Imperial Harem', 'Imperial Harem'),
 ('Incest', 'Incest'),
 ('Incubus', 'Incubus'),
 ('Indecisive Protagonist', 'Indecisive Protagonist'),
 ('Industrialization', 'Industrialization'),
 ('Inferiority Complex', 'Inferiority Complex'),
 ('Inheritance', 'Inheritance'),
 ('Inscriptions', 'Inscriptions'),
 ('Insects', 'Insects'),
 ('Interconnected Storylines', 'Interconnected Storylines'),
 ('Interdimensional Travel', 'Interdimensional Travel'),
 ('Introverted Protagonist', 'Introverted Protagonist'),
 ('Investigations', 'Investigations'),
 ('Invisibility', 'Invisibility'),
 ('Jack of All Trades', 'Jack of All Trades'),
 ('Jealousy', 'Jealousy'),
 ('Jiangshi', 'Jiangshi'),
 ('Jobless Class', 'Jobless Class'),
 ('JSDF', 'JSDF'),
 ('Kidnappings', 'Kidnappings'),
 ('Kind Love Interests', 'Kind Love Interests'),
 ('Kingdom Building', 'Kingdom Building'),
 ('Kingdoms', 'Kingdoms'),
 ('Knights', 'Knights'),
 ('Kuudere', 'Kuudere'),
 ('Lack of Common Sense', 'Lack of Common Sense'),
 ('Language Barrier', 'Language Barrier'),
 ('Late Romance', 'Late Romance'),
 ('Lawyers', 'Lawyers'),
 ('Lazy Protagonist', 'Lazy Protagonist'),
 ('Leadership', 'Leadership'),
 ('Legends', 'Legends'),
 ('Level System', 'Level System'),
 ('Library', 'Library'),
 ('Limited Lifespan', 'Limited Lifespan'),
 ('Living Abroad', 'Living Abroad'),
 ('Living Alone', 'Living Alone'),
 ('Loli', 'Loli'),
 ('Loneliness', 'Loneliness'),
 ('Loner Protagonist', 'Loner Protagonist'),
 ('Long Separations', 'Long Separations'),
 ('Long-distance Relationship', 'Long-distance Relationship'),
 ('Lost Civilizations', 'Lost Civilizations'),
 ('Lottery', 'Lottery'),
 ('Love at First Sight', 'Love at First Sight'),
 ('Love Interest Falls in Love First', 'Love Interest Falls in Love First'),
 ('Love Rivals', 'Love Rivals'),
 ('Love Triangles', 'Love Triangles'),
 ('Lovers Reunited', 'Lovers Reunited'),
 ('Low-key Protagonist', 'Low-key Protagonist'),
 ('Loyal Subordinates', 'Loyal Subordinates'),
 ('Lucky Protagonist', 'Lucky Protagonist'),
 ('Magic', 'Magic'),
 ('Magic Beasts', 'Magic Beasts'),
 ('Magic Formations', 'Magic Formations'),
 ('Magical Girls', 'Magical Girls'),
 ('Magical Space', 'Magical Space'),
 ('Magical Technology', 'Magical Technology'),
 ('Maids', 'Maids'),
 ('Male Protagonist', 'Male Protagonist'),
 ('Male to Female', 'Male to Female'),
 ('Male Yandere', 'Male Yandere'),
 ('Management', 'Management'),
 ('Mangaka', 'Mangaka'),
 ('Manipulative Characters', 'Manipulative Characters'),
 ('Manly Gay Couple', 'Manly Gay Couple'),
 ('Marriage', 'Marriage'),
 ('Marriage of Convenience', 'Marriage of Convenience'),
 ('Martial Spirits', 'Martial Spirits'),
 ('Masochistic Characters', 'Masochistic Characters'),
 ('Master-Disciple Relationship', 'Master-Disciple Relationship'),
 ('Master-Servant Relationship', 'Master-Servant Relationship'),
 ('Masturbation', 'Masturbation'),
 ('Matriarchy', 'Matriarchy'),
 ('Mature Protagonist', 'Mature Protagonist'),
 ('Medical Knowledge', 'Medical Knowledge'),
 ('Medieval', 'Medieval'),
 ('Mercenaries', 'Mercenaries'),
 ('Merchants', 'Merchants'),
 ('Military', 'Military'),
 ('Mind Break', 'Mind Break'),
 ('Mind Control', 'Mind Control'),
 ('Misandry', 'Misandry'),
 ('Mismatched Couple', 'Mismatched Couple'),
 ('Misunderstandings', 'Misunderstandings'),
 ('MMORPG', 'MMORPG'),
 ('Mob Protagonist', 'Mob Protagonist'),
 ('Models', 'Models'),
 ('Modern Day', 'Modern Day'),
 ('Modern Knowledge', 'Modern Knowledge'),
 ('Money Grubber', 'Money Grubber'),
 ('Monster Girls', 'Monster Girls'),
 ('Monster Society', 'Monster Society'),
 ('Monster Tamer', 'Monster Tamer'),
 ('Monsters', 'Monsters'),
 ('Movies', 'Movies'),
 ('Mpreg', 'Mpreg'),
 ('Multiple Identities', 'Multiple Identities'),
 ('Multiple Personalities', 'Multiple Personalities'),
 ('Multiple POV', 'Multiple POV'),
 ('Multiple Protagonists', 'Multiple Protagonists'),
 ('Multiple Realms', 'Multiple Realms'),
 ('Multiple Reincarnated Individuals', 'Multiple Reincarnated Individuals'),
 ('Multiple Timelines', 'Multiple Timelines'),
 ('Multiple Transported Individuals', 'Multiple Transported Individuals'),
 ('Murders', 'Murders'),
 ('Music', 'Music'),
 ('Mutated Creatures', 'Mutated Creatures'),
 ('Mutations', 'Mutations'),
 ('Mute Character', 'Mute Character'),
 ('Mysterious Family Background', 'Mysterious Family Background'),
 ('Mysterious Illness', 'Mysterious Illness'),
 ('Mysterious Past', 'Mysterious Past'),
 ('Mystery Solving', 'Mystery Solving'),
 ('Mythical Beasts', 'Mythical Beasts'),
 ('Mythology', 'Mythology'),
 ('Naive Protagonist', 'Naive Protagonist'),
 ('Narcissistic Protagonist', 'Narcissistic Protagonist'),
 ('Nationalism', 'Nationalism'),
 ('Near-Death Experience', 'Near-Death Experience'),
 ('Necromancer', 'Necromancer'),
 ('Neet', 'Neet'),
 ('Netorare', 'Netorare'),
 ('Netorase', 'Netorase'),
 ('Netori', 'Netori'),
 ('Nightmares', 'Nightmares'),
 ('Ninjas', 'Ninjas'),
 ('Nobles', 'Nobles'),
 ('Non-humanoid Protagonist', 'Non-humanoid Protagonist'),
 ('Non-linear Storytelling', 'Non-linear Storytelling'),
 ('Nudity', 'Nudity'),
 ('Nurses', 'Nurses'),
 ('Obsessive Love', 'Obsessive Love'),
 ('Office Romance', 'Office Romance'),
 ('Older Love Interests', 'Older Love Interests'),
 ('Omegaverse', 'Omegaverse'),
 ('Oneshot', 'Oneshot'),
 ('Online Romance', 'Online Romance'),
 ('Onmyouji', 'Onmyouji'),
 ('Orcs', 'Orcs'),
 ('Organized Crime', 'Organized Crime'),
 ('Orgy', 'Orgy'),
 ('Orphans', 'Orphans'),
 ('Otaku', 'Otaku'),
 ('Otome Game', 'Otome Game'),
 ('Outcasts', 'Outcasts'),
 ('Outdoor Intercourse', 'Outdoor Intercourse'),
 ('Outer Space', 'Outer Space'),
 ('Overpowered Protagonist', 'Overpowered Protagonist'),
 ('Overprotective Siblings', 'Overprotective Siblings'),
 ('Pacifist Protagonist', 'Pacifist Protagonist'),
 ('Paizuri', 'Paizuri'),
 ('Parallel Worlds', 'Parallel Worlds'),
 ('Parasites', 'Parasites'),
 ('Parent Complex', 'Parent Complex'),
 ('Parody', 'Parody'),
 ('Part-Time Job', 'Part-Time Job'),
 ('Past Plays a Big Role', 'Past Plays a Big Role'),
 ('Past Trauma', 'Past Trauma'),
 ('Persistent Love Interests', 'Persistent Love Interests'),
 ('Personality Changes', 'Personality Changes'),
 ('Perverted Protagonist', 'Perverted Protagonist'),
 ('Pets', 'Pets'),
 ('Pharmacist', 'Pharmacist'),
 ('Philosophical', 'Philosophical'),
 ('Phobias', 'Phobias'),
 ('Phoenixes', 'Phoenixes'),
 ('Photography', 'Photography'),
 ('Pill Based Cultivation', 'Pill Based Cultivation'),
 ('Pill Concocting', 'Pill Concocting'),
 ('Pilots', 'Pilots'),
 ('Pirates', 'Pirates'),
 ('Playboys', 'Playboys'),
 ('Playful Protagonist', 'Playful Protagonist'),
 ('Poetry', 'Poetry'),
 ('Poisons', 'Poisons'),
 ('Police', 'Police'),
 ('Polite Protagonist', 'Polite Protagonist'),
 ('Politics', 'Politics'),
 ('Polyandry', 'Polyandry'),
 ('Polygamy', 'Polygamy'),
 ('Poor Protagonist', 'Poor Protagonist'),
 ('Poor to Rich', 'Poor to Rich'),
 ('Popular Love Interests', 'Popular Love Interests'),
 ('Possession', 'Possession'),
 ('Possessive Characters', 'Possessive Characters'),
 ('Post-apocalyptic', 'Post-apocalyptic'),
 ('Power Couple', 'Power Couple'),
 ('Power Struggle', 'Power Struggle'),
 ('Pragmatic Protagonist', 'Pragmatic Protagonist'),
 ('Precognition', 'Precognition'),
 ('Pregnancy', 'Pregnancy'),
 ('Pretend Lovers', 'Pretend Lovers'),
 ('Previous Life Talent', 'Previous Life Talent'),
 ('Priestesses', 'Priestesses'),
 ('Priests', 'Priests'),
 ('Prison', 'Prison'),
 ('Proactive Protagonist', 'Proactive Protagonist'),
 ('Programmer', 'Programmer'),
 ('Prophecies', 'Prophecies'),
 ('Prostitutes', 'Prostitutes'),
 ('Protagonist Falls in Love First', 'Protagonist Falls in Love First'),
 ('Protagonist Strong from the Start', 'Protagonist Strong from the Start'),
 ('Protagonist with Multiple Bodies', 'Protagonist with Multiple Bodies'),
 ('Psychic Powers', 'Psychic Powers'),
 ('Psychopaths', 'Psychopaths'),
 ('Puppeteers', 'Puppeteers'),
 ('Quiet Characters', 'Quiet Characters'),
 ('Quirky Characters', 'Quirky Characters'),
 ('R-15', 'R-15'),
 ('R-18', 'R-18'),
 ('Race Change', 'Race Change'),
 ('Racism', 'Racism'),
 ('Rape', 'Rape'),
 ('Rape Victim Becomes Lover', 'Rape Victim Becomes Lover'),
 ('Rebellion', 'Rebellion'),
 ('Reincarnated as a Monster', 'Reincarnated as a Monster'),
 ('Reincarnated as an Object', 'Reincarnated as an Object'),
 ('Reincarnated in a Game World', 'Reincarnated in a Game World'),
 ('Reincarnated in Another World', 'Reincarnated in Another World'),
 ('Reincarnation', 'Reincarnation'),
 ('Religions', 'Religions'),
 ('Reluctant Protagonist', 'Reluctant Protagonist'),
 ('Reporters', 'Reporters'),
 ('Restaurant', 'Restaurant'),
 ('Resurrection', 'Resurrection'),
 ('Returning from Another World', 'Returning from Another World'),
 ('Revenge', 'Revenge'),
 ('Reverse Harem', 'Reverse Harem'),
 ('Reverse Rape', 'Reverse Rape'),
 ('Reversible Couple', 'Reversible Couple'),
 ('Rich to Poor', 'Rich to Poor'),
 ('Righteous Protagonist', 'Righteous Protagonist'),
 ('Rivalry', 'Rivalry'),
 ('Romantic Subplot', 'Romantic Subplot'),
 ('Roommates', 'Roommates'),
 ('Royalty', 'Royalty'),
 ('Ruthless Protagonist', 'Ruthless Protagonist'),
 ('Sadistic Characters', 'Sadistic Characters'),
 ('Saints', 'Saints'),
 ('Salaryman', 'Salaryman'),
 ('Samurai', 'Samurai'),
 ('Saving the World', 'Saving the World'),
 ('Schemes And Conspiracies', 'Schemes And Conspiracies'),
 ('Schizophrenia', 'Schizophrenia'),
 ('Scientists', 'Scientists'),
 ('Sculptors', 'Sculptors'),
 ('Sealed Power', 'Sealed Power'),
 ('Second Chance', 'Second Chance'),
 ('Secret Crush', 'Secret Crush'),
 ('Secret Identity', 'Secret Identity'),
 ('Secret Organizations', 'Secret Organizations'),
 ('Secret Relationship', 'Secret Relationship'),
 ('Secretive Protagonist', 'Secretive Protagonist'),
 ('Secrets', 'Secrets'),
 ('Sect Development', 'Sect Development'),
 ('Seduction', 'Seduction'),
 ('Seeing Things Other Humans Ca', 'Seeing Things Other Humans Ca'),
 ('', ''),
 ('Selfish Protagonist', 'Selfish Protagonist'),
 ('Selfless Protagonist', 'Selfless Protagonist'),
 ('Seme Protagonist', 'Seme Protagonist'),
 ('Senpai-Kouhai Relationship', 'Senpai-Kouhai Relationship'),
 ('Sentient Objects', 'Sentient Objects'),
 ('Sentimental Protagonist', 'Sentimental Protagonist'),
 ('Serial Killers', 'Serial Killers'),
 ('Servants', 'Servants'),
 ('Seven Deadly Sins', 'Seven Deadly Sins'),
 ('Seven Virtues', 'Seven Virtues'),
 ('Sex Friends', 'Sex Friends'),
 ('Sex Slaves', 'Sex Slaves'),
 ('Sexual Abuse', 'Sexual Abuse'),
 ('Sexual Cultivation Technique', 'Sexual Cultivation Technique'),
 ('Shameless Protagonist', 'Shameless Protagonist'),
 ('Shapeshifters', 'Shapeshifters'),
 ('Sharing A Body', 'Sharing A Body'),
 ('Sharp-tongued Characters', 'Sharp-tongued Characters'),
 ('Shield User', 'Shield User'),
 ('Shikigami', 'Shikigami'),
 ('Short Story', 'Short Story'),
 ('Shota', 'Shota'),
 ('Shoujo-Ai Subplot', 'Shoujo-Ai Subplot'),
 ('Shounen-Ai Subplot', 'Shounen-Ai Subplot'),
 ('Showbiz', 'Showbiz'),
 ('Shy Characters', 'Shy Characters'),
 ('Sibling Rivalry', 'Sibling Rivalry'),
 ('Siblin', 'Siblin'),
 (' Care', ' Care'),
 ('Siblings', 'Siblings'),
 ('Siblings Not Related by Blood', 'Siblings Not Related by Blood'),
 ('Sickly Characters', 'Sickly Characters'),
 ('Sign Language', 'Sign Language'),
 ('Singers', 'Singers'),
 ('Single Parent', 'Single Parent'),
 ('Sister Complex', 'Sister Complex'),
 ('Skill Assimilation', 'Skill Assimilation'),
 ('Skill Books', 'Skill Books'),
 ('Skill Creation', 'Skill Creation'),
 ('Slave Harem', 'Slave Harem'),
 ('Slave Protagonist', 'Slave Protagonist'),
 ('Slaves', 'Slaves'),
 ('Sleeping', 'Sleeping'),
 ('Slow Growth at Start', 'Slow Growth at Start'),
 ('Slow Romance', 'Slow Romance'),
 ('Smart Couple', 'Smart Couple'),
 ('Social Outcasts', 'Social Outcasts'),
 ('Soldiers', 'Soldiers'),
 ('Soul Power', 'Soul Power'),
 ('Souls', 'Souls'),
 ('Spatial Manipulation', 'Spatial Manipulation'),
 ('Spear Wielder', 'Spear Wielder'),
 ('Special Abilities', 'Special Abilities'),
 ('Spies', 'Spies'),
 ('Spirit Advisor', 'Spirit Advisor'),
 ('Spirit Users', 'Spirit Users'),
 ('Spirits', 'Spirits'),
 ('Stalkers', 'Stalkers'),
 ('Stockholm Syndrome', 'Stockholm Syndrome'),
 ('Stoic Characters', 'Stoic Characters'),
 ('Store Owner', 'Store Owner'),
 ('Straight Seme', 'Straight Seme'),
 ('Straight Uke', 'Straight Uke'),
 ('Strategic Battles', 'Strategic Battles'),
 ('Strategist', 'Strategist'),
 ('Strength-based Social Hierarchy', 'Strength-based Social Hierarchy'),
 ('Strong Love Interests', 'Strong Love Interests'),
 ('Strong to Stronger', 'Strong to Stronger'),
 ('Stubborn Protagonist', 'Stubborn Protagonist'),
 ('Student Council', 'Student Council'),
 ('Student-Teacher Relationship', 'Student-Teacher Relationship'),
 ('Succubus', 'Succubus'),
 ('Sudden Strength Gain', 'Sudden Strength Gain'),
 ('Sudden Wealth', 'Sudden Wealth'),
 ('Suicides', 'Suicides'),
 ('Summoned Hero', 'Summoned Hero'),
 ('Summoning Magic', 'Summoning Magic'),
 ('Survival', 'Survival'),
 ('Survival Game', 'Survival Game'),
 ('Sword And Magic', 'Sword And Magic'),
 ('Sword Wielder', 'Sword Wielder'),
 ('System Administrator', 'System Administrator'),
 ('Teachers', 'Teachers'),
 ('Teamwork', 'Teamwork'),
 ('Technological Gap', 'Technological Gap'),
 ('Tentacles', 'Tentacles'),
 ('Terminal Illness', 'Terminal Illness'),
 ('Terrorists', 'Terrorists'),
 ('Thieves', 'Thieves'),
 ('Threesome', 'Threesome'),
 ('Thriller', 'Thriller'),
 ('Time Loop', 'Time Loop'),
 ('Time Manipulation', 'Time Manipulation'),
 ('Time Paradox', 'Time Paradox'),
 ('Time Skip', 'Time Skip'),
 ('Time Travel', 'Time Travel'),
 ('Timid Protagonist', 'Timid Protagonist'),
 ('Tomboyish Female Lead', 'Tomboyish Female Lead'),
 ('Torture', 'Torture'),
 ('Toys', 'Toys'),
 ('Tragic Past', 'Tragic Past'),
 ('Transformation Ability', 'Transformation Ability'),
 ('Transmigration', 'Transmigration'),
 ('Transplanted Memories', 'Transplanted Memories'),
 ('Transported into a Game World', 'Transported into a Game World'),
 ('Transported Modern Structure', 'Transported Modern Structure'),
 ('Transported to Another World', 'Transported to Another World'),
 ('Trap', 'Trap'),
 ('Tribal Society', 'Tribal Society'),
 ('Trickster', 'Trickster'),
 ('Tsundere', 'Tsundere'),
 ('Twins', 'Twins'),
 ('Twisted Personality', 'Twisted Personality'),
 ('Ugly Protagonist', 'Ugly Protagonist'),
 ('Ugly to Beautiful', 'Ugly to Beautiful'),
 ('Unconditional Love', 'Unconditional Love'),
 ('Underestimated Protagonist', 'Underestimated Protagonist'),
 ('Unique Cultivation Technique', 'Unique Cultivation Technique'),
 ('Unique Weapon User', 'Unique Weapon User'),
 ('Unique Weapons', 'Unique Weapons'),
 ('Unlimited Flow', 'Unlimited Flow'),
 ('Unlucky Protagonist', 'Unlucky Protagonist'),
 ('Unreliable Narrator', 'Unreliable Narrator'),
 ('Unrequited Love', 'Unrequited Love'),
 ('Valkyries', 'Valkyries'),
 ('Vampires', 'Vampires'),
 ('Villainess Noble Girls', 'Villainess Noble Girls'),
 ('Virtual Reality', 'Virtual Reality'),
 ('Vocaloid', 'Vocaloid'),
 ('Voice Actors', 'Voice Actors'),
 ('Voyeurism', 'Voyeurism'),
 ('Waiters', 'Waiters'),
 ('War Records', 'War Records'),
 ('Wars', 'Wars'),
 ('Weak Protagonist', 'Weak Protagonist'),
 ('Weak to Strong', 'Weak to Strong'),
 ('Wealthy Characters', 'Wealthy Characters'),
 ('Werebeasts', 'Werebeasts'),
 ('Wishes', 'Wishes'),
 ('Witches', 'Witches'),
 ('Wizards', 'Wizards'),
 ('World Hopping', 'World Hopping'),
 ('World Travel', 'World Travel'),
 ('World Tree', 'World Tree'),
 ('Writers', 'Writers'),
 ('Yandere', 'Yandere'),
 ('Youkai', 'Youkai'),
 ('Younger Brothers', 'Younger Brothers'),
 ('Younger Love Interests', 'Younger Love Interests'),
 ('Younger Sisters', 'Younger Sisters'),
 ('Zombie', 'Zombie')]
    genrelist = [('Action', 'Action'),
 ('Adult', 'Adult'),
 ('Adventure', 'Adventure'),
 ('Comedy', 'Comedy'),
 ('Drama', 'Drama'),
 ('Ecchi', 'Ecchi'),
 ('Fantasy', 'Fantasy'),
 ('Gender Bender', 'Gender Bender'),
 ('Harem', 'Harem'),
 ('Historical', 'Historical'),
 ('Horror', 'Horror'),
 ('Josei', 'Josei'),
 ('Martial Arts', 'Martial Arts'),
 ('Mature', 'Mature'),
 ('Mecha', 'Mecha'),
 ('Mystery', 'Mystery'),
 ('Psychological', 'Psychological'),
 ('Romance', 'Romance'),
 ('School Life', 'School Life'),
 ('Sci-fi', 'Sci-fi'),
 ('Seinen', 'Seinen'),
 ('Shoujo', 'Shoujo'),
 ('Shoujo Ai', 'Shoujo Ai'),
 ('Shounen', 'Shounen'),
 ('Shounen Ai', 'Shounen Ai'),
 ('Slice of Life', 'Slice of Life'),
 ('Smut', 'Smut'),
 ('Sports', 'Sports'),
 ('Supernatural', 'Supernatural'),
 ('Tragedy', 'Tragedy'),
 ('Wuxia', 'Wuxia'),
 ('Xianxia', 'Xianxia'),
 ('Xuanhuan', 'Xuanhuan'),
 ('Yaoi', 'Yaoi'),
 ('Yuri', 'Yuri')]
    url = forms.URLField(label='URL', max_length=100)
    tags = forms.TypedMultipleChoiceField(choices=taglist,widget  = forms.CheckboxSelectMultiple)
    genres = forms.MultipleChoiceField(
        choices = genrelist, # this is optional
        widget  = forms.CheckboxSelectMultiple,
    )
